### Comprehensive Exercise on Tensors in PyTorch

#### **Exercise Title:** "Mastering Tensors in PyTorch: Initialization, Conversion, and Manipulation"

#### **Objective:** 
This exercise will solidify your understanding of PyTorch tensors by guiding you through key concepts such as initialization, conversion, property manipulation, and basic tensor operations.

---

### **Part 1: Tensor Initialization**
1. **Directly from Data:**
   - Create a 3x3 tensor using a nested list of integers ranging from 1 to 9.
   - Print the tensor and its datatype.

2. **From a NumPy Array:**
   - Create a NumPy array of shape `(2, 5)` with random integers between 0 and 10.
   - Convert the NumPy array to a PyTorch tensor.
   - Verify and print the shape and datatype of both the NumPy array and the tensor.

3. **From Another Tensor:**
   - Create a tensor of shape `(3, 3)` filled with random values.
   - Use this tensor to:
     - Create a new tensor filled with ones, retaining the shape and datatype of the original tensor.
     - Create another tensor filled with random values but change its datatype to `float32`.

4. **With Random or Constant Values:**
   - Initialize the following tensors:
     - A tensor of shape `(4, 4)` with random values.
     - A tensor of shape `(4, 4)` filled with ones.
     - A tensor of shape `(4, 4)` filled with zeros.
   - Print all tensors.

In [1]:
import torch
import numpy as np

In [6]:
# Part one solution:
## 1. Directly from Data:
tensor = torch.tensor([[1, 2, 3], 
                       [4, 5, 6], 
                       [7, 8, 9]])
print(f"3*3 tensor from a nested list:\n{tensor}")
print('#'*30)

## 2. from a numpy array:
np_array = np.random.randint(0, 10, size=(2, 5))
tensor_from_numpy = torch.from_numpy(np_array)
print(f"numpy array:\nshape-> {np_array.shape}\ttype-> {np_array.dtype}")
print(f"torch tensor:\nshape-> {tensor_from_numpy.shape}\ttype-> {tensor_from_numpy.dtype}")
print('#'*30)

## 3. from another tensors:
rand_tensor = torch.rand((3, 3))
ones_like_tensor = torch.ones_like(rand_tensor)
float_rand_tensor = torch.rand((3, 3), dtype=torch.float32)
print(f"ones tensor:\n{ones_like_tensor}\nfloat random values tensor:\n{float_rand_tensor}")
print('#'*30)

## 4. withr Random or Constant values:
shape =(4, 4,)
random_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"4x4 tensor with different initialization values:")
print(f"random values:\n{random_tensor}\nones tensor:\n{ones_tensor}\nzeros tensor:\n{zeros_tensor}")

3*3 tensor from a nested list:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
##############################
numpy array:
shape-> (2, 5)	type-> int32
torch tensor:
shape-> torch.Size([2, 5])	type-> torch.int32
##############################
ones tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
float random values tensor:
tensor([[0.9781, 0.0625, 0.0507],
        [0.2593, 0.5761, 0.6101],
        [0.2905, 0.0859, 0.6381]])
##############################
4x4 tensor with different initialization values:
random values:
tensor([[0.8011, 0.8672, 0.4740, 0.9923],
        [0.5955, 0.8761, 0.8243, 0.7407],
        [0.5650, 0.5454, 0.9311, 0.0324],
        [0.2973, 0.4667, 0.2561, 0.7294]])
ones tensor:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
zeros tensor:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


### **Part 2: Tensor Properties**
1. **Exploring Tensor Properties:**
   - Create a tensor of shape `(5, 5)` filled with random integers between 1 and 100.
   - Print the following properties of the tensor:
     - Shape
     - Datatype
     - Device (CPU or GPU)

2. **Reshaping Tensors:**
   - Reshape the tensor from the previous step into a shape `(25,)` (a 1D tensor).
   - Print the reshaped tensor and its new shape.

3. **Tensor Operations:**
   - Perform the following operations on a tensor of your choice:
     - Element-wise addition.
     - Matrix multiplication.
     - Transpose the tensor.
   - Print the results of each operation.


In [12]:
# Part two solution:
## 1. tensor properties:
rand_one_to_hundred = torch.randint(1, 100, size=(5, 5))
print(f"shape -> {rand_one_to_hundred.shape}")
print(f"Datatype -> {rand_one_to_hundred.dtype}")
print(f"Device -> {rand_one_to_hundred.device}")
print('#'*30)

## 2. Reshaping Tensors:
reshaped = rand_one_to_hundred.reshape((25, ))
print(f"reshaped tensor:\n{reshaped}\nsize -> {reshaped.shape}")
print('#'*30)

## 3. Tensor Operations:
tensor_1 = torch.tensor([[i for i in range(5)], [i for i in range(5, 10)]])
tensor_2 = torch.tensor([[i for i in range(5)], [i for i in range(5, 10)]])
one_plus_two = tensor_1 + tensor_2
mat_mul = torch.matmul(tensor_1, tensor_2.T)
tensor_1_T = tensor_1
print(f"Original Tensors:\nTensor 1:\n{tensor_1}\nTensor 2:\n{tensor_2}")
print(f"Addition:\n{one_plus_two}")
print(f"Matrix Multiplication:\n{mat_mul}")
print(f"Transpose of Tensor 1:\n{tensor_1_T}")

shape -> torch.Size([5, 5])
Datatype -> torch.int64
Device -> cpu
##############################
reshaped tensor:
tensor([14, 53, 96, 58, 63, 61, 94, 92, 24, 80, 60, 71, 90, 55, 80, 57, 75, 81,
        50, 41, 86, 47,  2, 63, 45])
size -> torch.Size([25])
##############################
Original Tensors:
Tensor 1:
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
Tensor 2:
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
Addition:
tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]])
Matrix Multiplication:
tensor([[ 30,  80],
        [ 80, 255]])
Transpose of Tensor 1:
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


### **Part 3: Conversion Between Tensors and NumPy**
1. **Tensor to NumPy:**
   - Create a tensor of shape `(3, 3)` with random floating-point numbers.
   - Convert this tensor to a NumPy array.
   - Verify that changes made to the NumPy array also affect the original tensor (and vice versa).

2. **NumPy to Tensor:**
   - Create a NumPy array of shape `(2, 2)` filled with random numbers.
   - Convert this array to a tensor and ensure that it shares memory with the NumPy array.

In [16]:
# Part three solution:
## 1. Tensor to Numpy:
rand_float_tensor = torch.rand((3, 3,))
numpy_version = rand_float_tensor.numpy()
print(f"Original Tensor:\n{rand_float_tensor}")
np.add(numpy_version, 3, out=numpy_version)
print(f"Original Tensor:\n{rand_float_tensor}")
print('#'*30)

## 2. Numpy to to Tensor:
rand_float_ndarray = np.random.rand(2, 2)
tensor_version = torch.from_numpy(rand_float_ndarray)
print(f"Original nd array:\n{rand_float_ndarray}")
tensor_version.add_(3)
print(f"Original nd array:\n{rand_float_ndarray}")

Original Tensor:
tensor([[0.1539, 0.8216, 0.6911],
        [0.4360, 0.1762, 0.3284],
        [0.7451, 0.3398, 0.6635]])
Original Tensor:
tensor([[3.1539, 3.8216, 3.6911],
        [3.4360, 3.1762, 3.3284],
        [3.7451, 3.3398, 3.6635]])
##############################
Original nd array:
[[0.53644016 0.67459349]
 [0.15003317 0.26981202]]
Original nd array:
[[3.53644016 3.67459349]
 [3.15003317 3.26981202]]


### **Part 4: Advanced Tensor Operations**
1. **Indexing and Slicing:**
   - Create a tensor of shape `(6, 6)` with random integers between 1 and 50.
   - Extract the following:
     - All elements in the first row.
     - All elements in the last column.
     - A sub-tensor containing rows 2-4 and columns 2-4.

2. **Broadcasting:**
   - Create two tensors of shapes `(3, 1)` and `(1, 4)`.
   - Add these tensors together and verify the resulting shape.

3. **GPU Tensors:**
   - If you have a GPU, create a tensor on the GPU.
   - Perform an operation (e.g., addition) on this tensor and transfer it back to the CPU.

In [22]:
# Part four solution:
## 1. Indexing and Slicing:
base_tensor = torch.randint(1, 50, (6, 6))
first_row_elements = base_tensor[0, :]
last_column_elements = base_tensor[:, -1]
sub_tensor = base_tensor[2:5, 2:5]
print(f"base tensor;\n{base_tensor}")
print(f"first row elements:\n{first_row_elements}")
print(f"last column elements:\n{last_column_elements}")
print(f"sub-tensor containing rows 2-4 and columns 2-4:\n{sub_tensor}")
print('#'*30)
## 2. Broadcasting:
t_1 = torch.ones((3, 1))
t_2 = torch.ones((1, 4))
print(f"t1:\n{t_1}")
print(f"t 2:\n{t_2}")
print(f"t1 + t2:\n{t_1+t_2}")
print("#"*30)

## 3. GPU Tensors
device = 'cuda' if torch.cuda.is_available() else 'cpu'
t_1 = t_1.to(device)
print(f"device -> {t_1.device}")

base tensor;
tensor([[15, 45, 28,  3, 41, 27],
        [38, 22, 20, 26, 11, 25],
        [ 5,  7, 21, 12, 30, 38],
        [17, 19, 24, 49, 19, 33],
        [30, 36, 14, 20,  1,  1],
        [28,  5, 40, 32, 23,  5]])
first row elements:
tensor([15, 45, 28,  3, 41, 27])
last column elements:
tensor([27, 25, 38, 33,  1,  5])
sub-tensor containing rows 2-4 and columns 2-4:
tensor([[21, 12, 30],
        [24, 49, 19],
        [14, 20,  1]])
##############################
t1:
tensor([[1.],
        [1.],
        [1.]])
t 2:
tensor([[1., 1., 1., 1.]])
t1 + t2:
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
##############################
device -> cpu


### **Expected Outcomes:**
By completing this exercise, you will:
1. Understand various ways to initialize tensors.
2. Master reshaping and converting tensors to/from NumPy arrays.
3. Perform tensor operations with confidence.